---
hosts:
  -
    settings:
      hostname: demo
      domain: startcloud.com
      server_id: '4020'
      vcpus: 2
      memory: 4G
      consoleport: 4020
      consolehost: 0.0.0.0
      box: 'STARTcloud/debian12-server'
      box_version: 0.0.3
      os_type: 'Debian_64'
      provider-type: virtualbox
      firmware_type: UEFI
      setup_wait: 300
      vagrant_user_private_key_path: ./id_rsa
      vagrant_user: startcloud
      vagrant_user_pass: 'STARTcloud22@!'
      vagrant_insert_key: true
      ssh_forward_agent: true

    networks:
      - type: external
        address: 192.168.2.227
        netmask: 255.255.255.0
        gateway:
        dhcp4: true
        dhcp6: false
        bridge:
        mac: auto
        dns:
          - nameserver: 9.9.9.9
          - nameserver: 149.112.112.112

    disks:
      boot:
        size: 24G
      additional_disks:
        - volume_name: disk1
          size: 20G
          port: 5

    provisioning:
      ansible.builtin.shell:
        enabled: false
        scripts:
          - './scripts/aliases.sh'

      ansible:
        enabled: true
        scripts:
          - local:
              - script: ansible/generate-playbook.yml
                ansible_python_interpreter: /usr/bin/python3
                compatibility_mode: 2.0
                install_mode: pip
                ssh_pipelining: true
                verbose: false
              - script: ansible/playbook.yml
                ansible_python_interpreter: /usr/bin/python3
                compatibility_mode: 2.0
                install_mode: pip
                ssh_pipelining: true
                verbose: false

    folders:
      - map: .
        to: /vagrant
        type: virtualbox
        disabled: true
        automount: true
        description: "Disable VBoxSF"
      - map: ./ansible/
        to: /vagrant/ansible/
        type: rsync
        args:
          - '--verbose'
          - '--archive'
          - '--delete'
          - '-z'
          - '--copy-links'
      - map: ./installers/
        to: /vagrant/installers/
        type: rsync
      - map: ./ssls/
        to: /secure/
        type: rsync
      - map: ./safe-id-to-cross-certify/
        to: /safe-id-to-cross-certify/
        type: rsync

    vars:
      domino_organization: STARTcloud
      domino_server_clustermates: 0
      safe_notes_id: SAFE.IDS
      domino_admin_notes_id_password: "password"
      selfsigned_enabled: false
      debug_all: true

      genesis_packages:
        - netmonitor
        - SuperHumanPortal

    roles:
      - name: startcloud_setup
      - name: startcloud_networking
      - name: startcloud_hostname
      - name: startcloud_dependencies
      - name: startcloud_service_user
      - name: startcloud_ssl
      - name: sdkman_install
      - name: sdkman_java
      - name: sdkman_maven
      - name: sdkman_gradle
      - name: domino_reset
      - name: domino_install
      - name: domino_vagrant_rest_api
      - name: domino_service_nash
      - name: domino_java_config
      - name: domino_java_tools
      - name: domino_updatesite
      - name: domino_config
      - name: domino_genesis
      - name: domino_genesis_applications
      - name: domino_cross_certify
      - name: domino_leap
      - name: domino_nomadweb
      - name: domino_traveler
      - name: domino_traveler_htmo
      - name: domino_verse
      - name: domino_appdevpack
      - name: domino_rest_api
      - name: domino_vagrant_readme
      - name: startcloud_quick_start
      - name: startcloud_vagrant_readme
      - name: startcloud_haproxy
      - name: startcloud_lockdown
